### DISCUSSION TITLE
source tags "changed" (not really) every sync run

### DISCUSSION THREAD

**Discussion by 4001982248998** [bb-Ricardo/netbox-sync#430] [Q&A]
this "change" is being applied on every sync run and on all hard disks, IP addresses and possibly more objects:

### before change
```yaml
tags: [
    "NetBox-synced",
    "Source: farm3"
]
```

### after change
```yaml
{
    "tags": [
        "NetBox-synced",
        "Source: farm3",
        "Source: farm3"
    ]
}
```
