### ISSUE TITLE
ERROR: Unable to determine NetBox version, HTTP header 'API-Version' missing.

### ISSUE THREAD

**Issue by xth0331** [bb-Ricardo/netbox-sync#314]
Netbox v3.5.1 is not supported, when I perform a sync, I get the following error.

```bash
ERROR: Unable to determine NetBox version, HTTP header 'API-Version' missing.
```

**Comment by bb-Ricardo** [comment]
Hi,

Haven't tested it with v3.5, will have a look what happend to the header.

**Comment by bb-Ricardo** [comment]
If I query the Netbox demo instance
```bash
curl -i -H "Content-Type: application/json" https://demo.netbox.dev/api/
```
I get
```yaml
HTTP/1.1 200 OK
Server: nginx/1.18.0 (Ubuntu)
Date: Fri, 12 May 2023 14:33:06 GMT
Content-Type: application/json
Content-Length: 532
Connection: keep-alive
Vary: Accept, Cookie, Origin
Allow: GET, HEAD, OPTIONS
X-Request-ID: db5b3dec-115b-410f-880a-ef5b220ac67b
API-Version: 3.5
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Cross-Origin-Opener-Policy: same-origin
X-Frame-Options: SAMEORIGIN
```

Can you try the same? it is important to include the `"Content-Type: application/json"` header
