### ISSUE TITLE
Mutiple VMware with same Datacenter and Cluster names

### ISSUE THREAD

**Issue by lucafabbri365** [bb-Ricardo/netbox-sync#438]
Hello,
I have two separate sites, each with a VMware Datacenter/Cluster with the same name.

**Site A**

- Datacenter name: **Datacenter**
- Cluster name: **Cluster**

**Site B**

- Datacenter name: **Datacenter**
- Cluster name: **Cluster**

How can I handle this with netbox-sync ?

Thank you very much.

**Comment by bb-Ricardo** [comment]
Hi,

You have to pre create them in NotBox with the correct configuration. But NetBox 4.2 API changed and netbox-sync does currently not provide support for it. I'm on it but will take a while.

**Comment by lucafabbri365** [comment]
Hello @bb-Ricardo,
take your time. I'll wait.

Thank you for your support guy !!!

**Comment by bb-Ricardo** [comment]
Hi,

I just pushed a new commit to the `development` branch. would you be able to test this?

In order for this to work for you, you need to create the sites in NetBox first.

Then create the clusters as well and use scope site and assign the sites accordingly.

Next you need to configure the `cluster_site_relation` to match your setup. see https://github.com/bb-Ricardo/netbox-sync/discussions/230

**Comment by lucafabbri365** [comment]
Hello @bb-Ricardo,
assuming I have:

_Site A_

- **VirtualCenter1**
  - Datacenter: **DC1**
    - Cluster: **CL1**

_Site B_

- **VirtualCenter2**
  - Datacenter: **DC1**
    - Cluster: **CL1**

I created, in NetBox, two Cluster objects with same name **DC1** and different scopes (_Site A_ and _Site B_). 
This is an excerpt from my `settings.yaml` file:

```
source:
   VirtualCenter1:
      type: vmware
      ...
      cluster_site_relation: CL1 = Site A
      ...
source:
   VirtualCenter2:
      type: vmware
      ...
     cluster_site_relation: CL1 = Site B
      ...
```

However, the first one is overwritten by the second VCSA instance.
Please, can you help me to understand what's wrong.

Thank you.

**Comment by bb-Ricardo** [comment]
Hi,

can you try this:
```yaml
source:
   VirtualCenter1:
      type: vmware
      ...
      cluster_site_relation: DC1/CL1 = Site A
      ...
source:
   VirtualCenter2:
      type: vmware
      ...
     cluster_site_relation: DC2/CL1 = Site B
      ...
```
the datacenter needs to part of this relation.
